routes/web.php
<?php


use Illuminate\Filesystem\Filesystem;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// app()->bind('example', function(){
//     return new \App\Example;
// });

// Route::get('/', function () {

//     dd(app('example'));

//     return view('welcome');
// });



Auth::routes();

// Route::get('/', 'PagesController@index')->name('homee');
// Route::get('/about', 'PagesController@about')->name('about');
// Route::get('/contact', 'PagesController@contact')->name('contact');
Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/home', 'HomeController@index')->name('home')-middleware('guest');


Route::get('/test', 'ProjectsController@test');
Route::get('/', 'ProjectsController@index');
Route::resource('projects', 'ProjectsController');



Route::post('/projects/{project}/tasks', 'ProjectTasksController@store');
Route::patch('/tasks/{task}', 'ProjectTasksController@update');




// Route::post('/projects', 'ProjectsController@store')->name('store');
// Route::get('/projects/create', 'ProjectsController@create');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = ['title', 'description', 'owner_id'];

    // protected $guarded = ['owner_id'];

    public function tasks() {

        return $this->hasMany(Task::class);
    }
    

    public function addTask($task) {

        $this->tasks()->create($task);

    }

}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;
use App\Project;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Filesystem\Filesystem;

class ProjectsController extends Controller
{

    public function __construct() {

        $this->middleware('auth');

        // $this->middleware('auth')->only(['store', ['update']]);
        // $this->middleware('auth')->except(['store', ['update']]);
    }


    public function index() {

       // auth()->id();  4

       // auth()->user();  user

       // auth()->check();  boolean

        //if (auth()->guest())

        // $projects = Project::where('owner_id', auth()->id())->paginate(5);

        $projects = auth()->user()->projects; // gets all the project for the auth user
        

        return view('projects.index', compact('projects'));
        // $posts = Post::orderBy('created_at', 'desc')->where('user_id', Auth::user()->id)->paginate(5);
        // $projects = Project::orderBy('created_at', 'desc')->paginate(5);
        // return view('projects.index')->with('projects', $projects);
    }

    public function create() {
        
        return view('projects/create');
    }

    public function store() {
        
        // $project = new Project();
        // $project->title = request('title');
        // $project->description = request('description'); 
        // $project->save();

        // request()->validate([
        //     'title' => ['required', 'min:3', 'max:255'],
        //     'description' => ['required', 'min:5', 'max:255']
        // ]);

        // request()->validate([
        //     'title' => ['required'],
        //     'description' => ['required']
        // ]);

        // Project::create(request(['title', 'description']));

        $validated = request()->validate([
            'title' => ['required'],
            'description' => ['required']
        ]);

        Project::create($validated + ['owner_id' => auth()->id()]);

        // $x = new Project;
        // $x->title = request()->title;
        // $x->description = request()->description;
        // // $x->owner_id = Auth::user()->id;
        // $x->save();

        return redirect('/projects');
    }

    public function show(Project $project) {

        // //$project = Project::findOrFail($id);

        // //dd($project);

        if ($project->owner_id == auth()->id() || auth()->id() == 1) {
            
            return view('projects.show', compact('project'));

        } else {

            abort(403);
        }

        // abort_if($project->owner_id !== auth()->id(), 403);

        
    }

    // public function show(Filesystem $file) {

    //     dd($file);
    // }
    
    public function edit(Project $project) {

        // $project = Project::findOrFail($id);

        return view('projects.edit', compact('project'));
    }

    public function update(Project $project) {

        // $project = Project::find($id);

        // $project->title = request('title');
        // $project->description = request('description');
        // $project->save();

        $validated = request()->validate([
            'title' => ['required'],
            'description' => ['required']
        ]);

        $project->update($validated);

        return redirect('/projects');
    }

    public function destroy(Project $project) {
        
        $project->delete();
        return redirect('/projects');
    }

    public function test() {

        return view('projects.test');
    }

    public function test2() {

        return view('projects.test2');
    }

    
}

resources/views/projects/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <h1>Create a new project</h1>

    <form method="POST" action="{{route('projects.store')}}">
        {{ csrf_field() }}
        <input type="text" name="title" placeholder="Title" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" value="{{old('title')}}">
        @if ($errors->has('title'))
            <span class="invalid-feedback" role="alert">
            <strong>{{ $errors->first('title') }}</strong>
            </span>
        @endif
        <br>
        <textarea rows="6" name="description" placeholder="Description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}">{{old('description')}}</textarea>
        @if ($errors->has('description'))
            <span class="invalid-feedback" role="alert">
            <strong>{{ $errors->first('description') }}</strong>
            </span>
        @endif
        <br>
        <button type="submit">Create Project</button>
        {{-- @include('errors') --}}
    </form>
</div>
    @endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<form method="POST" action="/projects/{{$project->id}}">
        <div class="form-group">
            {{method_field('PATCH')}}
            {{ csrf_field() }}
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="Title" value="{{$project->title}}">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <br>
        <textarea name="description" id="" cols="155" rows="10" value>{{$project->description}}</textarea>
            @include('errors')
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <form method="POST" action="/projects/{{$project->id}}"> 
        @method('DELETE')
        @csrf

        <button type="submit" class="btn btn-danger">Delete</button>
        </form>
</div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
<h1>Projects</h1>
<div class="row">
    @if(count($projects) > 0)
    @foreach ($projects as $project)
    <div class="col-sm-4">
        <div class="card">
            <h5 class="card-header">Featured</h5>
            <div class="card-body">
                <h5 class="card-title"><a href="projects/{{$project->id}}">{{$project->title}}</a></h5>
                <p class="card-text">
                    {{str_limit(strip_tags($project->description), 100)}}
                    @if (strlen(strip_tags($project->description)) > 100)
                    <br>
                    <a href="projects/{{$project->id}}">Show more</a>
                    @endif
                </p>
            </div>
        </div>
    </div>
    @endforeach
</div>
{{-- {{$projects->links()}} --}}
@else
<p>There is no post at the moment.</p>
@endif
</div>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
<h1>Show page</h1>
<div>
    Title: {{$project->title}}
</div>
<div>
    Title: {{$project->description}}
</div>
<a href="/projects/{{$project->id}}/edit">Edit</a>
@if($project->tasks->count()>0)

@foreach($project->tasks as $task)
<form method="POST" action="/tasks/{{$task->id}}">
    @method('PATCH')
    @csrf
    <div class="form-check"></div>
    <input type="checkbox" class="form-check-input" id="exampleCheck1" name="completed" onchange="this.form.submit();"
        {{$task->completed ? 'checked' : ''}}>
    {{$task->description}}
</form>
@endforeach
@endif
{{-- adding a new task --}}
<form method="POST" action="/projects/{{$project->id}}/tasks">
    {{ csrf_field() }}
    <input type="text" name="description" placeholder="Title" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}"
        value="{{old('title')}}">
    @if ($errors->has('description'))
    <span class="invalid-feedback" role="alert">
        <strong>{{ $errors->first('description') }}</strong>
    </span>
    @endif
    <br>
    <button type="submit">Create New Task</button>
    {{-- @include('errors') --}}
</form>
</div>
@endsection

resources/views/projects/test.blade.php
@extends('layouts.app')

@section('content')
    
@endsection 